#!/bin/sh
# pk's OS :: shutdown hook (unmounts the live media safely, so the USB/CD can be pulled
# out immediately)
sync
umount /live-iso 2>/dev/null
umount /live-base 2>/dev/null
umount /persistence 2>/dev/null
exit 0
