#!/bin/sh
# boot hook: if PK_DHCP=yes in /etc/default/pk, try DHCP
. /etc/default/pk 2>/dev/null
[ "${PK_DHCP:-no}" = yes ] || exit 0
[ -x /sbin/pk-net ] || exit 0
pk-net dhcp >/var/log/pk-net.log 2>&1 &
exit 0
